server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-connections: 20000
    max-threads: 1000
  servlet:
    context-path: /netty
spring:
    application:
        name: netty-server
        profiles:
          active: test
    main:
        allow-bean-definition-overriding: true
    #解决restful 404错误 spring.mvc.throw-exception-if-no-handler-found=true spring.resources.add-mappings=false
    mvc:
        throw-exception-if-no-handler-found: true
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
        add-mappings: false
    jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null



